export const AUDIT_ERROR_CODES = {
  INVALID_EVENT: 'AUDIT_INVALID_EVENT',
  LEDGER_MISMATCH: 'AUDIT_LEDGER_MISMATCH',
  EPOCH_MISMATCH: 'AUDIT_EPOCH_MISMATCH',
  EVENT_ID_CONFLICT: 'AUDIT_EVENT_ID_CONFLICT',
  APPEND_CONFLICT_EXHAUSTED: 'AUDIT_APPEND_CONFLICT_EXHAUSTED',
  JOURNAL_FAILURE: 'AUDIT_JOURNAL_FAILURE',
  EVIDENCE_FAILURE: 'AUDIT_EVIDENCE_FAILURE',
  EVIDENCE_INTEGRITY: 'AUDIT_EVIDENCE_INTEGRITY',
  EVIDENCE_LEGAL_HOLD: 'AUDIT_EVIDENCE_LEGAL_HOLD',
  EVIDENCE_ACCESS_DENIED: 'AUDIT_EVIDENCE_ACCESS_DENIED',
  CHECKPOINT_INVALID: 'AUDIT_CHECKPOINT_INVALID',
  CHECKPOINT_ROLLBACK: 'AUDIT_CHECKPOINT_ROLLBACK',
  CHECKPOINT_CONFLICT: 'AUDIT_CHECKPOINT_CONFLICT',
  CHECKPOINT_PUBLICATION_FAILED: 'AUDIT_CHECKPOINT_PUBLICATION_FAILED',
  PROJECTION_CONFLICT: 'AUDIT_PROJECTION_CONFLICT',
  MIRROR_VERIFICATION_FAILED: 'AUDIT_MIRROR_VERIFICATION_FAILED',
  MIRROR_CONTINUITY_FAILED: 'AUDIT_MIRROR_CONTINUITY_FAILED',
  MIRROR_OUT_OF_ORDER: 'AUDIT_MIRROR_OUT_OF_ORDER',
  UNAUTHORIZED_SUBMISSION: 'AUDIT_UNAUTHORIZED_SUBMISSION',
  INVALID_CONFIGURATION: 'AUDIT_INVALID_CONFIGURATION',
} as const;

export type AuditErrorCode = (typeof AUDIT_ERROR_CODES)[keyof typeof AUDIT_ERROR_CODES];

export class AuditProtocolError extends Error {
  constructor(
    readonly code: AuditErrorCode,
    message: string,
    readonly details?: Readonly<Record<string, unknown>>,
    options?: ErrorOptions,
  ) {
    super(message, options);
    this.name = 'AuditProtocolError';
  }
}
